export type VisaKind =
  | '留学'
  | '技術・人文知識・国際業務'
  | '家族滞在'
  | '日本人の配偶者等'
  | '経営・管理';

export type JLPT = 'N1' | 'N2' | 'N3' | 'N4' | 'N5' | '未取得';

export type Job = {
  id: string;
  title: string;
  company: string;
  salary: number; // 万円/年 の想定
  jlpt: JLPT;
  visaKind: VisaKind;
  // --- 追加でより現実的な表示に使うフィールド（任意） ---
  location?: string; // 勤務地
  employmentType?: '正社員' | '契約社員' | 'アルバイト' | '派遣' | '業務委託';
  workingHours?: string;
  holidays?: string;
  benefits?: string[];
  description?: string;
  requiredSkills?: string[];
  preferredSkills?: string[];
  companyLogo?: string; // public配下のパスなど
  companyWebsite?: string;
  companySize?: string; // 例: 50-100名
  industry?: string;
  postedDate?: string; // YYYY-MM-DD
  deadline?: string; // YYYY-MM-DD
  applicantCount?: number;
  lastUpdated?: string; // YYYY-MM-DD
  // 追加：より詳細な表示用
  salaryMin?: number; // 万円
  salaryMax?: number; // 万円
  summary?: string; // 一覧向けサマリ
  remote?: '不可' | '一部' | '可';
  status?: 'open' | 'closed';
  workLang?: '日本語' | '英語' | '日英併用';
  readingLevel?: '基礎' | '実務' | 'ビジネス';
  speakingLevel?: '基礎' | '実務' | 'ビジネス';
  visaSponsorship?: boolean; // ビザ支援の有無
  visaNotes?: string;
};

// デモ用に「技術・人文知識・国際業務 × N2」で複数件ヒットするよう調整
export const jobs: Job[] = [
  {
    id: 'j1',
    title: 'フロントエンドエンジニア',
    company: 'ACME KK',
    salary: 550,
    jlpt: 'N2',
    visaKind: '技術・人文知識・国際業務',
    location: '東京都渋谷区（リモート可）',
    employmentType: '正社員',
    workingHours: 'フレックスタイム（コア11:00-15:00）',
    holidays: '完全週休2日（土日祝）・年間休日120日',
    benefits: ['社会保険完備', 'リモート手当', '書籍購入補助'],
    description:
      '自社SaaSのUI改善、新機能開発。デザインと連携しUXを磨き込む役割です。コード品質と開発体験を大切にしています。',
    requiredSkills: ['React', 'TypeScript', 'CSS/Tailwind'],
    preferredSkills: ['Next.js', 'Storybook', 'E2Eテスト'],
    companySize: '100-300名',
    industry: 'IT・SaaS',
    postedDate: '2025-07-15',
    applicantCount: 23,
    lastUpdated: '2025-08-01',
    companyLogo: '/file.svg',
    companyWebsite: 'https://example.com',
    salaryMin: 500,
    salaryMax: 700,
    summary: '自社SaaSのUI/UX改善と新機能開発を推進するポジションです。',
    remote: '一部',
    status: 'open',
    workLang: '日英併用',
    readingLevel: 'ビジネス',
    speakingLevel: '実務',
    visaSponsorship: true,
    visaNotes: '更新支援あり・家族帯同相談可',
  },
  {
    id: 'j2',
    title: '通訳スタッフ',
    company: 'Globex',
    salary: 400,
    jlpt: 'N1',
    visaKind: '日本人の配偶者等',
    location: '神奈川県横浜市',
    employmentType: '契約社員',
    benefits: ['交通費全額支給'],
    description: '社内外の会議における日英通訳、資料翻訳業務。議事録作成や用語集管理も行います。',
    requiredSkills: ['日英通訳', '翻訳', '議事録作成'],
    preferredSkills: ['同時通訳', '用語集運用'],
    postedDate: '2025-07-20',
    lastUpdated: '2025-08-02',
    applicantCount: 5,
    companyLogo: '/globe.svg',
    salaryMin: 380,
    salaryMax: 480,
    summary: '会議通訳・資料翻訳を中心にコミュニケーションを支援。',
    remote: '一部',
    status: 'open',
    workLang: '日英併用',
    readingLevel: 'ビジネス',
    speakingLevel: 'ビジネス',
    visaSponsorship: true,
  },
  {
    id: 'j3',
    title: 'データアナリスト',
    company: 'Soylent',
    salary: 600,
    jlpt: 'N2',
    visaKind: '技術・人文知識・国際業務',
    location: '東京都港区',
    employmentType: '正社員',
    benefits: ['フルリモート可', '在宅手当'],
    description: '事業KPIの可視化、ダッシュボード構築、仮説検証を支援。',
    requiredSkills: ['SQL', 'Python', 'BIツール'],
    preferredSkills: ['dbt', 'BigQuery'],
    postedDate: '2025-07-10',
    applicantCount: 18,
    companyLogo: '/globe.svg',
    salaryMin: 550,
    salaryMax: 800,
    summary: 'データ分析で事業成長をドライブするアナリストを募集。',
    remote: '可',
    status: 'open',
    workLang: '日本語',
    readingLevel: '実務',
    speakingLevel: '実務',
    visaSponsorship: true,
  },
  {
    id: 'j4',
    title: '店舗スタッフ',
    company: 'Initech',
    salary: 350,
    jlpt: 'N3',
    visaKind: '留学',
    location: '千葉県船橋市',
    employmentType: 'アルバイト',
    description: '接客・販売・在庫管理。シフト柔軟。',
    requiredSkills: ['接客', 'レジ', '清掃'],
    preferredSkills: ['品出し', '在庫管理'],
    postedDate: '2025-08-01',
    applicantCount: 8,
    salaryMin: 320,
    salaryMax: 380,
    summary: '店舗運営に関わる接客・販売・在庫管理を担当。',
    remote: '不可',
    status: 'open',
    workLang: '日本語',
    readingLevel: '実務',
    speakingLevel: '実務',
    visaSponsorship: false,
  },
  {
    id: 'j5',
    title: 'バックエンドエンジニア',
    company: 'Umbrella',
    salary: 580,
    jlpt: 'N2',
    visaKind: '技術・人文知識・国際業務',
    location: '東京都新宿区',
    employmentType: '正社員',
    description: 'API設計・開発・運用。セキュリティとスケーラビリティを重視。',
    requiredSkills: ['Node.js', 'RDBMS', 'API設計'],
    preferredSkills: ['AWS', 'CI/CD'],
    postedDate: '2025-07-25',
    applicantCount: 12,
    companyLogo: '/window.svg',
    companyWebsite: 'https://example.com',
    salaryMin: 520,
    salaryMax: 750,
    summary: '堅牢なAPIプラットフォームの開発・運用を担うバックエンド。',
    remote: '一部',
    status: 'open',
    workLang: '日本語',
    readingLevel: 'ビジネス',
    speakingLevel: '実務',
    visaSponsorship: true,
  },
  // 追加データ（デモ用に複数条件で2〜3件ヒット）
  {
    id: 'j6',
    title: '営業アシスタント',
    company: 'Wayne Corp',
    salary: 420,
    jlpt: 'N1',
    visaKind: '日本人の配偶者等',
    location: '東京都中央区',
    employmentType: '正社員',
    description: '見積作成、受発注、請求処理、CRMの更新、営業資料の整備。',
    requiredSkills: ['Excel', 'CRM', 'コミュニケーション'],
    preferredSkills: ['営業事務', 'SAP'],
    postedDate: '2025-07-18',
    lastUpdated: '2025-07-31',
    applicantCount: 7,
    companyLogo: '/file.svg',
    salaryMin: 380,
    salaryMax: 460,
    summary: '営業部門の運営を支えるバックオフィス全般を担当。',
    remote: '一部',
    status: 'open',
    workLang: '日本語',
    readingLevel: 'ビジネス',
    speakingLevel: 'ビジネス',
    visaSponsorship: true,
  },
  {
    id: 'j7',
    title: 'カスタマーサポート',
    company: 'Stark Industries',
    salary: 430,
    jlpt: 'N1',
    visaKind: '日本人の配偶者等',
    location: '東京都品川区',
    employmentType: '正社員',
    description: 'メール・電話での問い合わせ対応、ナレッジベース整備、エスカレーション対応。',
    requiredSkills: ['顧客対応', 'Zendesk', '日本語対応'],
    preferredSkills: ['英語対応', 'FAQ作成'],
    postedDate: '2025-07-22',
    lastUpdated: '2025-08-01',
    applicantCount: 11,
    companyLogo: '/window.svg',
    salaryMin: 380,
    salaryMax: 480,
    summary: '顧客体験を高めるサポート運用とナレッジ管理。',
    remote: '可',
    status: 'open',
    workLang: '日本語',
    readingLevel: 'ビジネス',
    speakingLevel: 'ビジネス',
    visaSponsorship: true,
  },
  {
    id: 'j8',
    title: 'カフェスタッフ',
    company: 'Dunder Mifflin',
    salary: 320,
    jlpt: 'N3',
    visaKind: '留学',
    location: '東京都杉並区',
    employmentType: 'アルバイト',
    description: 'カフェ運営全般（接客、レジ、清掃、簡単な仕込み）',
    requiredSkills: ['接客', 'レジ', '清掃'],
    preferredSkills: ['バリスタ'],
    postedDate: '2025-08-02',
    applicantCount: 4,
    salaryMin: 280,
    salaryMax: 360,
    summary: '地域密着のカフェでのホール・レジ・清掃業務。',
    remote: '不可',
    status: 'open',
    workLang: '日本語',
    readingLevel: '基礎',
    speakingLevel: '実務',
    visaSponsorship: false,
  },
  {
    id: 'j9',
    title: '経営企画アシスタント',
    company: 'Tyrell Corp',
    salary: 700,
    jlpt: 'N1',
    visaKind: '経営・管理',
    location: '東京都千代田区',
    employmentType: '正社員',
    description: 'KPI管理、予実分析、経営会議資料の作成、各部門との調整。',
    requiredSkills: ['Excel', 'PowerPoint', '会計基礎'],
    preferredSkills: ['英語', 'SQL'],
    postedDate: '2025-07-12',
    lastUpdated: '2025-07-30',
    applicantCount: 10,
    companyLogo: '/globe.svg',
    salaryMin: 600,
    salaryMax: 800,
    summary: '経営判断を支える分析・資料作成を担当。',
    remote: '一部',
    status: 'open',
    workLang: '日本語',
    readingLevel: 'ビジネス',
    speakingLevel: 'ビジネス',
    visaSponsorship: true,
  },
  {
    id: 'j10',
    title: '管理部マネージャー',
    company: 'Oscorp',
    salary: 800,
    jlpt: 'N1',
    visaKind: '経営・管理',
    location: '東京都港区',
    employmentType: '正社員',
    description: '総務・人事・法務の統括、体制構築、マネジメント。',
    requiredSkills: ['労務', '法務基礎', 'マネジメント'],
    preferredSkills: ['上場企業対応', '内部統制'],
    postedDate: '2025-07-05',
    lastUpdated: '2025-07-25',
    applicantCount: 6,
    salaryMin: 750,
    salaryMax: 900,
    summary: 'バックオフィス全体を牽引する管理部門の要職。',
    remote: '一部',
    status: 'open',
    workLang: '日本語',
    readingLevel: 'ビジネス',
    speakingLevel: 'ビジネス',
    visaSponsorship: true,
  },
  {
    id: 'j11',
    title: '製造ラインスタッフ',
    company: 'Wonka',
    salary: 340,
    jlpt: 'N4',
    visaKind: '家族滞在',
    location: '埼玉県川口市',
    employmentType: '契約社員',
    description: '製造ラインのオペレーション、検品、清掃。安全第一の現場です。',
    requiredSkills: ['安全意識', '体力', 'チームワーク'],
    preferredSkills: ['フォークリフト'],
    postedDate: '2025-07-28',
    applicantCount: 3,
    salaryMin: 320,
    salaryMax: 360,
    summary: '食品製造ラインでのオペレーション業務。',
    remote: '不可',
    status: 'open',
    workLang: '日本語',
    readingLevel: '実務',
    speakingLevel: '実務',
    visaSponsorship: false,
  },
  {
    id: 'j12',
    title: '物流スタッフ',
    company: 'MomCorp',
    salary: 360,
    jlpt: 'N4',
    visaKind: '家族滞在',
    location: '千葉県市川市',
    employmentType: '契約社員',
    description: '倉庫での入出庫、ピッキング、在庫管理。',
    requiredSkills: ['フォークリフト', 'ピッキング', '在庫管理'],
    preferredSkills: ['Excel'],
    postedDate: '2025-07-27',
    applicantCount: 5,
    salaryMin: 330,
    salaryMax: 390,
    summary: '物流センターでの入出庫・在庫管理を担当。',
    remote: '不可',
    status: 'open',
    workLang: '日本語',
    readingLevel: '実務',
    speakingLevel: '実務',
    visaSponsorship: false,
  },
  {
    id: 'j13',
    title: 'QAエンジニア',
    company: 'Hooli',
    salary: 520,
    jlpt: 'N3',
    visaKind: '技術・人文知識・国際業務',
    location: '東京都目黒区',
    employmentType: '正社員',
    description: 'テスト設計、手動/自動テスト、品質指標の管理。',
    requiredSkills: ['テスト設計', 'Jest', '品質管理'],
    preferredSkills: ['Playwright', 'CI'],
    postedDate: '2025-07-17',
    lastUpdated: '2025-07-31',
    applicantCount: 9,
    salaryMin: 480,
    salaryMax: 650,
    summary: 'サービス品質を支えるQA活動全般を担当。',
    remote: '一部',
    status: 'open',
    workLang: '日本語',
    readingLevel: 'ビジネス',
    speakingLevel: '実務',
    visaSponsorship: true,
  },
  {
    id: 'j14',
    title: 'Webエンジニア',
    company: 'Pied Piper',
    salary: 590,
    jlpt: 'N3',
    visaKind: '技術・人文知識・国際業務',
    location: '東京都渋谷区',
    employmentType: '正社員',
    description: 'フロントエンド中心にWebアプリ開発。API連携、パフォーマンス改善。',
    requiredSkills: ['JavaScript', 'React', 'API'],
    preferredSkills: ['Next.js', 'GraphQL'],
    postedDate: '2025-07-16',
    lastUpdated: '2025-08-01',
    applicantCount: 14,
    salaryMin: 520,
    salaryMax: 760,
    summary: 'プロダクトのWeb体験を高める開発を担当。',
    remote: '可',
    status: 'open',
    workLang: '日本語',
    readingLevel: 'ビジネス',
    speakingLevel: '実務',
    visaSponsorship: true,
  },
  {
    id: 'j15',
    title: '販売スタッフ',
    company: 'Nakatomi Trading',
    salary: 330,
    jlpt: 'N5',
    visaKind: '家族滞在',
    location: '東京都港区',
    employmentType: 'アルバイト',
    description: '店頭での接客、品出し、レジ対応。',
    requiredSkills: ['接客', '品出し'],
    preferredSkills: ['中国語'],
    postedDate: '2025-08-03',
    applicantCount: 2,
    salaryMin: 300,
    salaryMax: 360,
    summary: '小売店舗での接客・販売サポート。',
    remote: '不可',
    status: 'open',
    workLang: '日本語',
    readingLevel: '基礎',
    speakingLevel: '実務',
    visaSponsorship: false,
  },
  {
    id: 'j16',
    title: '事務スタッフ',
    company: 'Initrode',
    salary: 380,
    jlpt: 'N2',
    visaKind: '日本人の配偶者等',
    location: '東京都新宿区',
    employmentType: '契約社員',
    description: '資料作成、スケジュール調整、データ入力、電話対応。',
    requiredSkills: ['Excel', '事務処理', 'コミュニケーション'],
    preferredSkills: ['英語'],
    postedDate: '2025-07-21',
    applicantCount: 6,
    salaryMin: 360,
    salaryMax: 420,
    summary: '部門の事務業務全般を幅広くサポート。',
    remote: '一部',
    status: 'open',
    workLang: '日本語',
    readingLevel: 'ビジネス',
    speakingLevel: '実務',
    visaSponsorship: false,
  },
  {
    id: 'j17',
    title: '研究アシスタント',
    company: 'Aperture Science',
    salary: 540,
    jlpt: 'N2',
    visaKind: '留学',
    location: '東京都文京区',
    employmentType: '契約社員',
    description: '研究室での実験補助、データ記録、器具管理、安全管理。',
    requiredSkills: ['実験補助', '記録', '安全管理'],
    preferredSkills: ['英語読解'],
    postedDate: '2025-07-29',
    applicantCount: 4,
    salaryMin: 500,
    salaryMax: 600,
    summary: '研究活動を支えるアシスタント業務。',
    remote: '不可',
    status: 'open',
    workLang: '日本語',
    readingLevel: '実務',
    speakingLevel: '実務',
    visaSponsorship: true,
  },
  {
    id: 'j18',
    title: 'PMアシスタント',
    company: 'Massive Dynamic',
    salary: 610,
    jlpt: 'N2',
    visaKind: '経営・管理',
    location: '東京都港区',
    employmentType: '正社員',
    description: 'プロジェクトの進行管理、議事録作成、資料整備、ステークホルダー調整。',
    requiredSkills: ['スケジュール管理', '議事録', '調整力'],
    preferredSkills: ['Jira', '英語'],
    postedDate: '2025-07-14',
    lastUpdated: '2025-07-29',
    applicantCount: 8,
    salaryMin: 560,
    salaryMax: 700,
    summary: 'PMを支える運用・コミュニケーションのハブ役。',
    remote: '一部',
    status: 'open',
    workLang: '日英併用',
    readingLevel: 'ビジネス',
    speakingLevel: '実務',
    visaSponsorship: true,
  },
  {
    id: 'j19',
    title: '通訳（社内）',
    company: 'LexCorp',
    salary: 450,
    jlpt: 'N1',
    visaKind: '技術・人文知識・国際業務',
    location: '東京都千代田区（リモート一部可）',
    employmentType: '正社員',
    benefits: ['社会保険完備', '交通費全額支給', '在宅手当'],
    description:
      '社内外会議における日英同時・逐次通訳、社内資料・契約書等の翻訳、議事録作成、海外拠点とのブリッジコミュニケーションを担当します。専門用語の整備と用語集の継続更新も行い、各部門の意思決定を言語面から支援します。',
    requiredSkills: ['日英通訳（会議）', '翻訳（技術/ビジネス）', '議事録作成'],
    preferredSkills: ['用語集運用', '通訳機材の基本知識', 'プロジェクト調整'],
    companyLogo: '/globe.svg',
    salaryMin: 420,
    salaryMax: 550,
    summary: '社内外会議の通訳・翻訳を中心に、海外拠点と事業部の連携を言語面からリード。',
    remote: '一部',
    status: 'open',
    workLang: '日英併用',
    readingLevel: 'ビジネス',
    speakingLevel: 'ビジネス',
    visaSponsorship: true,
    postedDate: '2025-07-28',
    lastUpdated: '2025-08-02',
    applicantCount: 9,
  },
  {
    id: 'j20',
    title: '人事アシスタント',
    company: 'Vandelay Industries',
    salary: 410,
    jlpt: 'N2',
    visaKind: '家族滞在',
    location: '東京都品川区',
    employmentType: '契約社員',
    description: '入退社手続き、勤怠・給与データの取りまとめ、採用補助。',
    requiredSkills: ['人事事務', '労務', 'Excel'],
    preferredSkills: ['英語', '社会保険手続'],
    postedDate: '2025-07-23',
    lastUpdated: '2025-08-01',
    applicantCount: 7,
    salaryMin: 380,
    salaryMax: 450,
    summary: '人事・労務まわりの運用を支えるアシスタント。',
    remote: '一部',
    status: 'open',
    workLang: '日本語',
    readingLevel: 'ビジネス',
    speakingLevel: '実務',
    visaSponsorship: false,
  },
];

export type Application = {
  name: string;
  nationality: string;
  birthDate: string; // YYYY-MM-DD
  gender?: string;
  passportNumber?: string;
  passportExpiry?: string; // YYYY-MM-DD
  visaKind: VisaKind;
  expiryDate: string; // YYYY-MM-DD
  jlpt: JLPT;
  // 動的フィールド用
  dynamicFields?: Record<string, string>;
  // 企業担当者メール
  companyContactEmail?: string;
};


